dist: xenial
language: go
go:
  - stable
  - master

matrix:
  allow_failures:
    - go: master

env:
  - GO111MODULE=on

install:
  - sudo apt-get install wget
  - sudo apt-get install libegl1-mesa-dev libgl1-mesa-dev
  - sudo apt-get install libusb-1.0-0-dev libfreenect-dev
  -
  - go get -u golang.org/x/lint/golint

before_script:
  - go mod download
script:
  - gofmt -s -d .
  - go build -tags kinect ./cmd/shady/
  - go test -test.v -race ./...
  - go vet ./...
  - golint -min_confidence 0.3 $(go list ./...)
