[[constraint]]
  branch = "master"
  name = "github.com/go-gl/gl"

[[constraint]]
  branch = "master"
  name = "github.com/mjibson/go-dsp"

[[constraint]]
  branch = "master"
  name = "github.com/tarm/serial"
