[[constraint]]
  name = "github.com/go-gl/gl"
  branch = "master"

[[constraint]]
  name = "github.com/mjibson/go-dsp"
  branch = "master"

[[constraint]]
  name = "github.com/tarm/serial"
  branch = "master"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"
