name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    env:
      GOPATH: /home/runner/go

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - run: go get -u golang.org/x/lint/golint
    - run: sudo apt install libegl1-mesa-dev libgl1-mesa-dev libglfw3-dev
    - run: sudo apt install libxcursor-dev libxinerama-dev libxi-dev libxxf86vm-dev
    - run: sudo apt install libusb-1.0-0-dev libfreenect-dev
    - run: go mod download

    - name: Check go mod
      run: |
        go mod tidy
        git diff --exit-code go.mod
        git diff --exit-code go.sum

    - run: gofmt -s -d .
    - run: $GOPATH/bin/golint -min_confidence 0.3 $(go list ./...)
    - run: go build -tags kinect ./cmd/shady/
    - run: go test -test.v -race -cover ./...
